plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pianokid.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.pianokid.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
